name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkouts@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: setup-java@v4
        with:
          ditribution: temurin
          java-version: 11
          cache: gradle
      - run: |
          chmod +x ./gradlew
          ./gradlew :module:assembleRelease
      - uses: actions/upload-artifact@v4
        with:
          name: zygisk-imgui-menu
          path: out/magisk_module_release?
        
